# Generated by Django 3.0.7 on 2020-06-15 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kickdUpApi', '0002_auto_20200615_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
