# Generated by Django 3.0.7 on 2020-06-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickdUpApi', '0003_auto_20200615_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerpost',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kickdUpApi.Manufacturer'),
        ),
    ]
