# Generated by Django 3.0.7 on 2020-06-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickdUpApi', '0005_auto_20200623_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sneakerpost',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to='kickdUpApi.SneakerPost'),
        ),
    ]
