# Generated by Django 3.0.7 on 2020-06-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickdUpApi', '0006_auto_20200624_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='kickdUpApi.SneakerPost'),
        ),
    ]
